language: php
sudo: false
php:
    - 5.6
    - 7.0
before_install:
    - composer self-update
    - composer require phpunit/phpunit:~5.5
install:
    - composer install --dev
script:
    - phpunit --coverage-text
